apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: strategy-volume
  labels:
    app: strategy-volume
spec:
  storageClassName: geneva-cephfs-testing
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
